"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createSupabaseServerClient, hasSupabaseConfig } from "@/lib/supabase/server";
import {
  activateTemplate,
  buildPreviewForRequest,
  createGuestRequest,
  downloadGeneratedDocumentBytes,
  downloadTemplateBytes,
  getActiveTemplate,
  getCondoSettings,
  getRequestById,
  getResidentProfile,
  getTemplateById,
  recordEmailSend,
  saveTemplateMappings,
  updateResidentAndSettings,
  uploadGeneratedDocument,
  uploadTemplateFile,
} from "@/lib/data";
import { detectPdfFields, fillPdfTemplate } from "@/lib/pdf";
import { sendGuestAuthorizationEmail } from "@/lib/email";
import type { ReadySendField } from "@/lib/types";

function requireConfiguredServices() {
  if (!hasSupabaseConfig()) {
    throw new Error("Configure Supabase environment variables before using this workflow.");
  }
}

export async function signInAction(formData: FormData) {
  const email = String(formData.get("email") ?? "").trim();
  const password = String(formData.get("password") ?? "");
  const next = String(formData.get("next") ?? "/dashboard");

  const supabase = await createSupabaseServerClient();
  if (!supabase) {
    redirect("/dashboard");
  }

  const { error } = await supabase.auth.signInWithPassword({ email, password });
  if (error) {
    redirect(`/login?error=${encodeURIComponent(error.message)}`);
  }

  redirect(next.startsWith("/") ? next : "/dashboard");
}

export async function signOutAction() {
  const supabase = await createSupabaseServerClient();
  await supabase?.auth.signOut();
  redirect("/login");
}

export async function saveSettingsAction(formData: FormData) {
  requireConfiguredServices();
  await updateResidentAndSettings(formData);
  revalidatePath("/settings");
  revalidatePath("/dashboard");
}

export async function uploadTemplateAction(formData: FormData) {
  requireConfiguredServices();
  const file = formData.get("template_pdf");
  if (!(file instanceof File) || file.size === 0) {
    throw new Error("Choose a PDF template to upload.");
  }
  if (file.type && file.type !== "application/pdf") {
    throw new Error("Template upload must be a PDF.");
  }

  const buffer = await file.arrayBuffer();
  const detectedFields = await detectPdfFields(buffer);
  await uploadTemplateFile(file, detectedFields);
  revalidatePath("/settings");
}

export async function saveTemplateMappingsAction(formData: FormData) {
  requireConfiguredServices();
  const templateId = String(formData.get("template_id") ?? "");
  const pdfFieldNames = formData.getAll("pdf_field_name").map(String);
  const readySendFields = formData.getAll("ready_send_field").map(String);

  const mappings = pdfFieldNames
    .map((pdfFieldName, index) => ({
      pdfFieldName,
      readySendField: readySendFields[index] as ReadySendField,
    }))
    .filter((mapping) => mapping.pdfFieldName && mapping.readySendField);

  await saveTemplateMappings(templateId, mappings);
  revalidatePath("/settings");
}

export async function generateTemplateTestAction(formData: FormData) {
  requireConfiguredServices();
  const templateId = String(formData.get("template_id") ?? "");
  const template = await getTemplateById(templateId);
  if (!template) throw new Error("Template not found.");
  if (!template.mappings.length) throw new Error("Save at least one template field mapping first.");

  const [resident, settings] = await Promise.all([getResidentProfile(), getCondoSettings()]);
  const sampleRequest = {
    id: "template-test",
    guests: [
      { name: "Sarah Miller", relation: "Mother-in-law" },
      { name: "Clara Miller", relation: "Sister" },
    ],
    visitDate: new Date().toISOString().slice(0, 10),
    startTime: "10:00",
    endTime: "16:00",
    parkingNotes: resident.parking,
    specialInstructions: "Template test generated by Ready Send.",
    status: "draft" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  const templateBytes = await downloadTemplateBytes(template);
  const generatedBytes = await fillPdfTemplate({
    templateBytes,
    template,
    resident,
    settings,
    request: sampleRequest,
  });
  const document = await uploadGeneratedDocument({
    requestId: "template-test",
    templateId: template.id,
    filename: `test-${template.name}`,
    bytes: generatedBytes,
    isTest: true,
  });
  await activateTemplate(template.id, document.storagePath);
  revalidatePath("/settings");
  revalidatePath("/request");
}

export async function createGuestRequestAction(formData: FormData) {
  requireConfiguredServices();
  const requestId = await createGuestRequest(formData);
  revalidatePath("/history");
  redirect(`/preview?requestId=${requestId}`);
}

export async function generateDocumentAction(formData: FormData) {
  requireConfiguredServices();
  const requestId = String(formData.get("request_id") ?? "");
  const request = await getRequestById(requestId);
  const template = await getActiveTemplate();
  if (!request) throw new Error("Request not found.");
  if (!template) throw new Error("No active PDF template is configured.");
  if (!template.mappings.length) throw new Error("The active template has no field mappings.");

  const [resident, settings, templateBytes] = await Promise.all([
    getResidentProfile(),
    getCondoSettings(),
    downloadTemplateBytes(template),
  ]);
  const generatedBytes = await fillPdfTemplate({
    templateBytes,
    template,
    resident,
    settings,
    request,
  });
  await uploadGeneratedDocument({
    requestId,
    templateId: template.id,
    filename: `guest-authorization-${resident.unit.toLowerCase()}-${requestId.slice(0, 8)}.pdf`,
    bytes: generatedBytes,
  });
  revalidatePath("/preview");
  revalidatePath("/history");
  redirect(`/preview?requestId=${requestId}`);
}

export async function sendEmailAction(formData: FormData) {
  requireConfiguredServices();
  const requestId = String(formData.get("request_id") ?? "");
  const request = await getRequestById(requestId);
  if (!request) throw new Error("Request not found.");
  if (!request.generatedDocument) {
    throw new Error("Generate a PDF before sending.");
  }

  const preview = await buildPreviewForRequest(request, request.generatedDocument);
  const attachmentBytes = await downloadGeneratedDocumentBytes(request.generatedDocument);

  let sent = false;
  try {
    const providerMessageId = await sendGuestAuthorizationEmail({ preview, attachmentBytes });
    await recordEmailSend({
      requestId,
      generatedDocumentId: request.generatedDocument.id,
      providerMessageId,
      status: "sent",
      recipient: preview.to,
      replyTo: preview.replyTo,
      subject: preview.subject,
      body: preview.body,
      errorMessage: null,
    });
    sent = true;
    revalidatePath("/history");
    revalidatePath("/dashboard");
  } catch (error) {
    await recordEmailSend({
      requestId,
      generatedDocumentId: request.generatedDocument.id,
      providerMessageId: null,
      status: "failed",
      recipient: preview.to,
      replyTo: preview.replyTo,
      subject: preview.subject,
      body: preview.body,
      errorMessage: error instanceof Error ? error.message : "Unknown send error",
    });
    revalidatePath("/history");
    redirect(`/preview?requestId=${requestId}&error=send-failed`);
  }

  if (sent) {
    redirect(`/success?requestId=${requestId}`);
  }
}
